stages:
  - build

darwin-ventura-arm64-build:
  stage: build
  tags:
    - darwin, arm64
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5 -DPython3_ROOT_DIR=/opt/homebrew/opt/python@3 -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON 2>&1 | tee configure.log
    - cmake --build . --parallel 10 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

darwin-monterey-intel-build:
  stage: build
  tags:
    - darwin, intel
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/Homebrew/opt/qt@5 -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=/opt/Homebrew/Frameworks/Python.framework/Versions/3.11/bin/python3 -DWITH_PYTHON=ON
    - cmake --build . --parallel 12 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

ubuntu-bionic-build:
  stage: build
  image: iffregistry.fz-juelich.de/kholostov/qtisas:latest
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON 2>&1 | tee configure.log
    - cmake --build . 2>&1 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log
