stages:
  - .pre
  - build
  - sync

ubuntu-jammy-sast:
  stage: .pre
  image: iffregistry.fz-juelich.de/qtisas/qtisas:jammy-0.0.2
  script:
    - git submodule update --init --recursive
    - mkdir libs
    - tar -xvf /root/Linux-x86_64.tar.xz -C libs
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release -DPython3_ROOT_DIR=/root/venv-qtisas/bin/ -DWITH_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - mkdir -p qtisas_autogen/include
    - uic ../qtisas/sans/ascii1d/ascii1d.ui -o qtisas_autogen/include/ui_ascii1d.h
    - uic ../qtisas/sans/compile/compile.ui -o qtisas_autogen/include/ui_compile.h
    - uic ../qtisas/sans/dan/dan.ui -o qtisas_autogen/include/ui_dan.h
    - uic ../qtisas/sans/fittable/fittable.ui -o qtisas_autogen/include/ui_fittable.h
    - uic ../qtisas/sans/jnse/jnse.ui -o qtisas_autogen/include/ui_jnse.h
    - uic ../qtisas/sans/svd/svd.ui -o qtisas_autogen/include/ui_svd.h
    - source /root/venv-qtisas/bin/activate
    - python3 ../scripts/sast.py

ubuntu-jammy-format:
  stage: .pre
  image: iffregistry.fz-juelich.de/qtisas/qtisas:jammy-0.0.2
  script:
    - source /root/venv-qtisas/bin/activate
    - python3 scripts/clang_format.py

darwin-ventura-arm64-build:
  stage: build
  tags:
    - darwin, arm64
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt@5 -DPython3_ROOT_DIR=/opt/homebrew/opt/python@3 -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON 2>&1 | tee configure.log
    - cmake --build . --parallel 10 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

darwin-monterey-intel-build:
  stage: build
  tags:
    - darwin, intel
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_PREFIX_PATH=/opt/Homebrew/opt/qt@5 -DCMAKE_BUILD_TYPE=Release -DPython3_EXECUTABLE=/opt/Homebrew/Frameworks/Python.framework/Versions/3.11/bin/python3 -DWITH_PYTHON=ON
    - cmake --build . --parallel 12 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

ubuntu-bionic-build:
  stage: build
  image: iffregistry.fz-juelich.de/qtisas/qtisas:bionic-0.0.4
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON 2>&1 | tee configure.log
    - cmake --build . 2>&1 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

rocky9-build:
  stage: build
  image: iffregistry.fz-juelich.de/qtisas/qtisas:rocky9-0.0.1
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON 2>&1 | tee configure.log
    - cmake --build . 2>&1 | tee build.log
  artifacts:
    paths:
      - build/configure.log
      - build/build.log

ubuntu-jammy-sync:
  stage: sync
  image: iffregistry.fz-juelich.de/qtisas/qtisas:jammy-0.0.1
  rules:
    - if: '$CI_PROJECT_ID == "1655" && $CI_PIPELINE_SOURCE != "merge_request_event"'
  script:
    - git remote add mirror https://$GITHUB_TOKEN@github.com/k61n/qtisas.git
    - git fetch mirror
    - git push -f mirror HEAD:master
