stages:
  - .pre
  - build
  - tag
  - deploy
  - upload
  - release
  - sync

SAST:
  stage: .pre
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_DESCRIPTION !~ /.pre=skip/ && $CI_PROJECT_ID != "1655"'
  tags:
    - darwin, arm64, ventura
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/homebrew/bin/cmake
      ..
      -G"Ninja"
      -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/homebrew/opt/gl2ps
      -DGSL_ROOT=/opt/homebrew/opt/gsl
      -DHDF5_ROOT=/opt/homebrew/opt/hdf5
      -Dmuparser_ROOT=/opt/homebrew/opt/muparser
      -DTIFF_ROOT=/opt/homebrew/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/homebrew/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt
      -DPython3_ROOT_DIR=/opt/homebrew/opt/python@3
      -DWITH_PYTHON=ON
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - mkdir -p qtisas_autogen/include
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/ascii1d/ascii1d.ui -o qtisas_autogen/include/ui_ascii1d.h
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/compile/compile.ui -o qtisas_autogen/include/ui_compile.h
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/dan/dan.ui -o qtisas_autogen/include/ui_dan.h
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/fittable/fittable.ui -o qtisas_autogen/include/ui_fittable.h
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/jnse/jnse.ui -o qtisas_autogen/include/ui_jnse.h
    - /opt/homebrew/opt/qt/share/qt/libexec/uic ../qtisas/sans/svd/svd.ui -o qtisas_autogen/include/ui_svd.h
    - python3 ../scripts/sast.py

clang-format:
  stage: .pre
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_DESCRIPTION !~ /.pre=skip/ && $CI_PROJECT_ID != "1655"'
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/util:15
  script:
    - python3 scripts/clang_format.py

macos:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - { ARCH: "arm64", SDK: MacOSX.sdk }
      - { ARCH: "arm64", SDK: MacOSX13.3.sdk }
      - { ARCH: "intel", SDK: MacOSX.sdk }
  tags:
    - darwin, $ARCH, ventura
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/homebrew/bin/cmake
      ..
      -G"Ninja"
      -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/homebrew/opt/gl2ps
      -DGSL_ROOT=/opt/homebrew/opt/gsl
      -DHDF5_ROOT=/opt/homebrew/opt/hdf5
      -Dmuparser_ROOT=/opt/homebrew/opt/muparser
      -DTIFF_ROOT=/opt/homebrew/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/homebrew/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current
      -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/$SDK
      -DCMAKE_IGNORE_PATH=/usr/local
      -DCMAKE_IGNORE_PREFIX_PATH=/usr/local
      -DCMAKE_SYSTEM_IGNORE_PATH=/usr/local
      -DCMAKE_SYSTEM_IGNORE_PREFIX_PATH=/usr/local
      -DCMAKE_CXX_FLAGS="-I/opt/homebrew/include"
    - /opt/homebrew/bin/cmake --build . --parallel $(sysctl -n hw.ncpu)

windows:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - { ARCH: "x64", TOOL: "msvc2022_64", USER: "admin" }
      - { ARCH: "arm64", TOOL: "msvc2022_arm64", USER: "jcns" }
  tags:
    - win, $ARCH
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
      -DBUILD_SHARED_LIBS=ON
      -Dgl2ps_ROOT="C:/qtisas_libs/$TOOL/gl2ps"
      -DGSL_ROOT="C:/qtisas_libs/$TOOL/gsl"
      -DHDF5_ROOT="C:/qtisas_libs/$TOOL/hdf5"
      -Dmuparser_ROOT="C:/qtisas_libs/$TOOL/muparser"
      -DTIFF_ROOT="C:/qtisas_libs/$TOOL/tiff"
      -Dyaml-cpp_ROOT="C:/qtisas_libs/$TOOL/yaml_cpp"
      -DZLIB_ROOT="C:/qtisas_libs/$TOOL/zlib"
      -DCMAKE_PREFIX_PATH="C:/Qt/6.9.2/$TOOL"
      -DPython3_ROOT_DIR="C:/Users/$USER/AppData/Local/Programs/Python/Python313"
      -DWITH_PYTHON=ON
    - cmake.exe --build . --config Release

linux:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - IMAGE: ["debian11:6", "ubuntu24.04:7", "rocky9:14"]
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/$IMAGE
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON
    - cmake --build . --parallel 4

tag:
  stage: tag
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID == "1655"'
  image: alpine/git
  script:
    - git config --global user.name "CI"
    - git config --global user.email "k.kholostov@fz-juelich.de"
    - git_version=$(git describe --tags --abbrev=0)
    - local_version=$(head -n 1 changelog.md | sed 's/^# //')
    - if [ "$local_version" != "$git_version" ]; then git tag $local_version && git push https://$TAGGING@$(echo $CI_PROJECT_URL | sed 's/^https:\/\///').git --tags; fi

obs-release:
  stage: deploy
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/util:15
  only:
    - tags@qtisas/qtisas
  script:
    - cd ..
    - echo "user=$OBS_USER" | tee -a /etc/osc/oscrc >/dev/null
    - echo "pass=$OBS_TOKEN" | tee -a /etc/osc/oscrc >/dev/null
    - mkdir -p ~/.config/osc
    - ln -s /etc/osc/oscrc ~/.config/osc
    - osc co $OBS_PROJECT
    - cp qtisas/install/linux/_service $OBS_PROJECT
    - osc commit $OBS_PROJECT/_service -m "$CI_COMMIT_TAG"
  allow_failure: true

macos-release:
  stage: deploy
  parallel:
    matrix:
      - { ARCH: "arm64", }
      - { ARCH: "intel", }
  tags:
    - darwin, $ARCH, ventura
  only:
    - tags@qtisas/qtisas
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/homebrew/bin/cmake
      ..
      -G"Ninja"
      -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/homebrew/opt/gl2ps
      -DGSL_ROOT=/opt/homebrew/opt/gsl
      -DHDF5_ROOT=/opt/homebrew/opt/hdf5
      -Dmuparser_ROOT=/opt/homebrew/opt/muparser
      -DTIFF_ROOT=/opt/homebrew/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/homebrew/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=~/Qt/6.9.2/macos
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current
      -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk
      -DCMAKE_IGNORE_PATH=/usr/local
      -DCMAKE_IGNORE_PREFIX_PATH=/usr/local
      -DCMAKE_SYSTEM_IGNORE_PATH=/usr/local
      -DCMAKE_SYSTEM_IGNORE_PREFIX_PATH=/usr/local
      -DCMAKE_CXX_FLAGS="-I/opt/homebrew/include"
    - /opt/homebrew/bin/cmake --build . --parallel $(sysctl -n hw.ncpu)
    - cd ../bin
    - /opt/homebrew/opt/qt/bin/macdeployqt qtisas.app -verbose=3 || true
    - ver=$(/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current/bin/python3 --version | awk '{print $2}' | cut -d. -f1,2)
    - install_name_tool -change @rpath/Python3.framework/Versions/$ver/Python3
        /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Python3
        qtisas.app/Contents/MacOS/qtisas
    - cp ../install/osx/Info.plist_release qtisas.app/Contents/Info.plist
    - cp ../install/osx/launcher qtisas.app/Contents/MacOS
    - mkdir -p qtisas.app/Contents/Resources/python/site-packages
    - cp -r venv/lib/python$ver/site-packages/PyQt6 qtisas.app/Contents/Resources/python/site-packages
    - rm -rf qtisas.app/Contents/Frameworks/*.framework
    - rm -rf qtisas.app/Contents/plugins
    - cd qtisas.app/Contents/Frameworks
    - for dir in ../Resources/python/site-packages/PyQt6/Qt6/lib/*.framework; do ln -s $dir $(basename $dir); done
    - cd ..
    - ln -s Resources/python/site-packages/PyQt6/Qt6/plugins plugins
    - cd ../../..
    - codesign --deep --force --verify --verbose --sign "qtisas" bin/qtisas.app
    - if [ -d "/Volumes/qtisas" ]; then hdiutil detach /Volumes/qtisas; fi
    - hdiutil create -size 500m -fs HFS+ -volname "qtisas" -attach ./qtisas.dmg
    - mv bin/qtisas.app /Volumes/qtisas
    - ln -s /Applications /Volumes/qtisas/Applications
    - rm -rf /Volumes/qtisas/.fseventsd
    - hdiutil detach /Volumes/qtisas
    - hdiutil convert ./qtisas.dmg -format UDZO -o qtisas-$CI_COMMIT_TAG-$ARCH.dmg
  artifacts:
    paths:
      - qtisas-$CI_COMMIT_TAG-$ARCH.dmg

windows-release:
  stage: deploy
  parallel:
    matrix:
      - { ARCH: "x64", A: "AMD64", TOOL: "msvc2022_64", USER: "admin" }
      - { ARCH: "arm64", A: "ARM64", TOOL: "msvc2022_arm64", USER: "jcns" }
  tags:
    - win, $ARCH
  only:
    - tags@qtisas/qtisas
  script:
    - $env:Path = "C:\Qt\6.9.2\$TOOL\bin;" + $env:Path
    - $env:Path = "C:\Qt\Tools\QtInstallerFramework\4.10\bin;" + $env:Path
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
      -DBUILD_SHARED_LIBS=ON
      -Dgl2ps_ROOT="C:/qtisas_libs/$TOOL/gl2ps"
      -DGSL_ROOT="C:/qtisas_libs/$TOOL/gsl"
      -DHDF5_ROOT="C:/qtisas_libs/$TOOL/hdf5"
      -Dmuparser_ROOT="C:/qtisas_libs/$TOOL/muparser"
      -DTIFF_ROOT="C:/qtisas_libs/$TOOL/tiff"
      -Dyaml-cpp_ROOT="C:/qtisas_libs/$TOOL/yaml_cpp"
      -DZLIB_ROOT="C:/qtisas_libs/$TOOL/zlib"
      -DCMAKE_PREFIX_PATH="C:/Qt/6.9.2/$TOOL"
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR="C:\Users\$USER\AppData\Local\Programs\Python\Python313"
    - cmake --build . --config Release
    - cd ..
    - copy bin\Release\qtisas.exe install\win\packages\com.qtisas\data
    - windeployqt install\win\packages\com.qtisas\data\qtisas.exe
    - mkdir install\win\packages\com.qtisas\data\icons
    - copy qtisas\icons\qtisas.ico install\win\packages\com.qtisas\data\icons\qtisas.ico
    - copy libs\Windows-$A\minigzip\bin\minigzip.dll install\win\packages\com.qtisas\data
    - copy libs\Windows-$A\qtexengine\bin\qtexengine.dll install\win\packages\com.qtisas\data
    - copy libs\Windows-$A\qwt\bin\qwt.dll install\win\packages\com.qtisas\data
    - copy libs\Windows-$A\qwtplot3d\bin\qwtplot3d.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\gl2ps\bin\gl2ps.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\gsl\bin\gsl.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\gsl\lib\gsl.lib install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\gsl\bin\gslcblas.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\gsl\lib\gslcblas.lib install\win\packages\com.qtisas\data
    - Copy-Item -Path C:\qtisas_libs\$TOOL\gsl\include\gsl -Destination install\win\packages\com.qtisas\data -Recurse
    - copy C:\qtisas_libs\$TOOL\hdf5\bin\hdf5.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\hdf5\bin\hdf5_cpp.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\muparser\bin\muparser.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\libjpeg\bin\jpeg62.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\tiff\bin\tiff.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\xz\bin\liblzma.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\yaml_cpp\bin\yaml-cpp.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\zlib\bin\zlib.dll install\win\packages\com.qtisas\data
    - copy C:\qtisas_libs\$TOOL\zstd\bin\zstd.dll install\win\packages\com.qtisas\data
    - mkdir install\win\packages\com.qtisas\data\python
    - copy qtisas\python\qtisasrc.py install\win\packages\com.qtisas\data\python
    - copy qtisas\python\python-qtiUtil.py install\win\packages\com.qtisas\data\python
    - copy qtisas\python\qti_wordlist.txt install\win\packages\com.qtisas\data\python
    - $pythonPath="bin\venv\Scripts\python.exe"; $pyVersion = (& $pythonPath --version) -replace '^Python\s+',''
    - $pyqtOutput = & $pythonPath -m pip show PyQt6; $pyqtVersion = ($pyqtOutput | ForEach-Object { if ($_ -match '^Version:\s*(.+)$') { $matches[1] } })
    - (Get-Content "install\win\packages\com.python\meta\package.xml") -replace "__PYQT_VERSION__", $pyqtVersion -replace "__PY_VERSION__", $pyVersion | Set-Content "install\win\packages\com.python\meta\package.xml"
    - (Get-Content "install\win\packages\com.python\meta\installscript.qs") -replace "__PYQT_VERSION__", $pyqtVersion -replace "__PY_VERSION__", $pyVersion | Set-Content "install\win\packages\com.python\meta\installscript.qs"
    - binarycreator -c install\win\config\config.xml -p install\win\packages qtisas-$CI_COMMIT_TAG-$ARCH.exe --verbose
  artifacts:
    paths:
      - qtisas-$CI_COMMIT_TAG-$ARCH.exe

upload:
  stage: upload
  image: curlimages/curl:latest
  only:
    - tags@qtisas/qtisas
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-arm64.dmg "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.dmg"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-intel.dmg "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-intel.dmg"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-arm64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.exe"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-x64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-x64.exe"'
  needs: ["macos-release: [arm64]",
          "macos-release: [intel]",
          "windows-release: [arm64, ARM64, msvc2022_arm64, jcns]",
          "windows-release: [x64, AMD64, msvc2022_64, admin]"]

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags@qtisas/qtisas
  script:
    - echo "Release CI stage for $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: $CI_COMMIT_TAG
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: 'qtisas-$CI_COMMIT_TAG-arm64.dmg'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.dmg'
        - name: 'qtisas-$CI_COMMIT_TAG-intel.dmg'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-intel.dmg'
        - name: 'qtisas-$CI_COMMIT_TAG-arm64.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.exe'
        - name: 'qtisas-$CI_COMMIT_TAG-x64.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-x64.exe'
  needs: ["upload"]

sync:
  stage: sync
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID == "1655"'
  image: alpine/git
  script:
    - git remote add mirror https://$GITHUB_TOKEN@github.com/k61n/qtisas.git
    - git fetch mirror
    - git push -f mirror HEAD:master
    - git push -f mirror --delete $(git ls-remote --tags mirror | awk -F/ '{print $NF}')
    - git push mirror --tags
