stages:
  - .pre
  - build
  - tag
  - deploy
  - upload
  - release
  - sync

SAST:
  stage: .pre
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_DESCRIPTION !~ /.pre=skip/ && $CI_PROJECT_ID != "1655"'
  tags:
    - darwin, arm64, ventura
  script:
    - eval "$(/opt/homebrew/bin/brew shellenv)"
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/homebrew/bin/cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/homebrew/opt/gl2ps
      -DGSL_ROOT=/opt/homebrew/opt/gsl
      -DHDF5_ROOT=/opt/homebrew/opt/hdf5
      -Dmuparser_ROOT=/opt/homebrew/opt/muparser
      -DTIFF_ROOT=/opt/homebrew/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/homebrew/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=/opt/homebrew/opt/qt
      -DPython3_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current
      -DWITH_PYTHON=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - mkdir -p qtisas_autogen/include
    - uic ../qtisas/sans/ascii1d/ascii1d.ui -o qtisas_autogen/include/ui_ascii1d.h
    - uic ../qtisas/sans/compile/compile.ui -o qtisas_autogen/include/ui_compile.h
    - uic ../qtisas/sans/dan/dan.ui -o qtisas_autogen/include/ui_dan.h
    - uic ../qtisas/sans/fittable/fittable.ui -o qtisas_autogen/include/ui_fittable.h
    - uic ../qtisas/sans/jnse/jnse.ui -o qtisas_autogen/include/ui_jnse.h
    - uic ../qtisas/sans/svd/svd.ui -o qtisas_autogen/include/ui_svd.h
    - python3 ../scripts/sast.py

clang-format:
  stage: .pre
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_DESCRIPTION !~ /.pre=skip/ && $CI_PROJECT_ID != "1655"'
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/util:0.0.14
  script:
    - python3 scripts/clang_format.py

macos:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - { ARCH: "arm64", BREW: "homebrew" }
      - { ARCH: "intel", BREW: "homebrew-x86" }
  tags:
    - darwin, $ARCH, ventura
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/$BREW/bin/cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/$BREW/opt/gl2ps
      -DGSL_ROOT=/opt/$BREW/opt/gsl
      -DHDF5_ROOT=/opt/$BREW/opt/hdf5
      -Dmuparser_ROOT=/opt/$BREW/opt/muparser
      -DTIFF_ROOT=/opt/$BREW/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/$BREW/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=/opt/$BREW/opt/qt
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current
    - /opt/$BREW/bin/cmake --build . --parallel $(sysctl -n hw.ncpu)

windows:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - { ARCH: "x64", TOOL: "msvc2022_64", USER: "admin" }
      - { ARCH: "arm64", TOOL: "msvc2022_arm64", USER: "jcns" }
  tags:
    - win, $ARCH
  script:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
      -Dgl2ps_ROOT="C:/qtisas_libs/$TOOL/gl2ps"
      -DGSL_ROOT="C:/qtisas_libs/$TOOL/gsl"
      -DHDF5_ROOT="C:/qtisas_libs/$TOOL/hdf5"
      -Dmuparser_ROOT="C:/qtisas_libs/$TOOL/muparser"
      -DTIFF_ROOT="C:/qtisas_libs/$TOOL/tiff"
      -Dyaml-cpp_ROOT="C:/qtisas_libs/$TOOL/yaml_cpp"
      -DZLIB_ROOT="C:/qtisas_libs/$TOOL/zlib"
      -DCMAKE_PREFIX_PATH="C:/Qt/6.8.3/$TOOL"
      -DPython3_ROOT_DIR="C:/Users/$USER/AppData/Local/Programs/Python/Python312"
      -DWITH_PYTHON=ON
    - cmake.exe --build . --config Release

linux:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID != "1655"'
  parallel:
    matrix:
      - IMAGE: ["debian11:0.0.5", "noble:0.0.6", "rocky9:0.0.13"]
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/$IMAGE
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON
    - cmake --build . --parallel 4

tag:
  stage: tag
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID == "1655"'
  image: alpine/git
  script:
    - git config --global user.name "CI"
    - git config --global user.email "k.kholostov@fz-juelich.de"
    - git_version=$(git describe --tags --abbrev=0)
    - local_version=$(head -n 1 changelog.md | sed 's/^# //')
    - if [ "$local_version" != "$git_version" ]; then git tag $local_version && git push https://$TAGGING@$(echo $CI_PROJECT_URL | sed 's/^https:\/\///').git --tags; fi

obs-release:
  stage: deploy
  image: iffregistry.fz-juelich.de/qtisas/qtisas-ci/util:0.0.7
  only:
    - tags@qtisas/qtisas
  script:
    - cd ..
    - echo "user=$OBS_USER" | tee -a /etc/osc/oscrc >/dev/null
    - echo "pass=$OBS_TOKEN" | tee -a /etc/osc/oscrc >/dev/null
    - mkdir -p ~/.config/osc
    - ln -s /etc/osc/oscrc ~/.config/osc
    - osc co $OBS_PROJECT
    - cp qtisas/linux/_service $OBS_PROJECT
    - osc commit $OBS_PROJECT/_service -m "$CI_COMMIT_TAG"
  allow_failure: true

macos-release:
  stage: deploy
  parallel:
    matrix:
      - { ARCH: "arm64", BREW: "homebrew" }
      - { ARCH: "intel", BREW: "homebrew-x86" }
  tags:
    - darwin, $ARCH, ventura
  only:
    - tags@qtisas/qtisas
  script:
    - git submodule update --init --recursive
    - mkdir build && cd build
    - /opt/$BREW/bin/cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
      -Dgl2ps_ROOT=/opt/$BREW/opt/gl2ps
      -DGSL_ROOT=/opt/$BREW/opt/gsl
      -DHDF5_ROOT=/opt/$BREW/opt/hdf5
      -Dmuparser_ROOT=/opt/$BREW/opt/muparser
      -DTIFF_ROOT=/opt/$BREW/opt/libtiff
      -Dyaml-cpp_ROOT=/opt/$BREW/opt/yaml-cpp
      -DCMAKE_PREFIX_PATH=/opt/$BREW/opt/qt
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current
    - /opt/$BREW/bin/cmake --build . --parallel $(sysctl -n hw.ncpu)
    - cd ../bin
    - /opt/$BREW/opt/qt/bin/macdeployqt qtisas.app -verbose=3 || true
    - cp -r /opt/$BREW/opt/qt/share/qt/plugins qtisas.app/Contents
    - install_name_tool -change @rpath/libhdf5.310.dylib
      @executable_path/../Frameworks/libhdf5.310.dylib
      qtisas.app/Contents/Frameworks/libhdf5_cpp.310.dylib
    - ver=$(/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/Current/bin/python3 --version | awk '{print $2}' | cut -d. -f1,2)
    - install_name_tool -change @rpath/Python3.framework/Versions/$ver/Python3
        /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Python3
        qtisas.app/Contents/MacOS/qtisas
    - codesign --deep --force --verify --verbose --sign "qtisas" qtisas.app
    - mv qtisas.app ../
    - cd ..
    - if [ -d "/Volumes/qtisas" ]; then hdiutil detach /Volumes/qtisas; fi
    - hdiutil create -size 200m -fs HFS+ -volname "qtisas" -attach ./qtisas.dmg
    - mv qtisas.app /Volumes/qtisas
    - ln -s /Applications /Volumes/qtisas/Applications
    - rm -rf /Volumes/qtisas/.fseventsd
    - hdiutil detach /Volumes/qtisas
    - hdiutil convert ./qtisas.dmg -format UDZO -o qtisas-$CI_COMMIT_TAG-$ARCH.dmg
  artifacts:
    paths:
      - qtisas-$CI_COMMIT_TAG-$ARCH.dmg

windows-release:
  stage: deploy
  parallel:
    matrix:
      - { ARCH: "x64", A: "AMD64", TOOL: "msvc2022_64", USER: "admin" }
      - { ARCH: "arm64", A: "ARM64", TOOL: "msvc2022_arm64", USER: "jcns" }
  tags:
    - win, $ARCH
  only:
    - tags@qtisas/qtisas
  script:
    - $env:Path = "C:\Qt\6.8.3\$TOOL\bin;" + $env:Path
    - $env:Path = "C:\Qt\Tools\QtInstallerFramework\4.8\bin;" + $env:Path
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake ..
      -Dgl2ps_ROOT="C:/qtisas_libs/$TOOL/gl2ps"
      -DGSL_ROOT="C:/qtisas_libs/$TOOL/gsl"
      -DHDF5_ROOT="C:/qtisas_libs/$TOOL/hdf5"
      -Dmuparser_ROOT="C:/qtisas_libs/$TOOL/muparser"
      -DTIFF_ROOT="C:/qtisas_libs/$TOOL/tiff"
      -Dyaml-cpp_ROOT="C:/qtisas_libs/$TOOL/yaml_cpp"
      -DZLIB_ROOT="C:/qtisas_libs/$TOOL/zlib"
      -DCMAKE_PREFIX_PATH="C:/Qt/6.8.3/$TOOL"
      -DWITH_PYTHON=ON
      -DPython3_ROOT_DIR="C:\Users\$USER\AppData\Local\Programs\Python\Python312"
    - cmake --build . --config Release
    - cd ..
    - copy bin\Release\qtisas.exe win\packages\com.qtisas\data
    - windeployqt win\packages\com.qtisas\data\qtisas.exe
    - mkdir win\packages\com.qtisas\data\icons
    - copy qtisas\icons\qtisas.ico win\packages\com.qtisas\data\icons\qtisas.ico
    - copy libs\Windows-$A\minigzip\bin\minigzip.dll win\packages\com.qtisas\data\
    - copy libs\Windows-$A\qtexengine\bin\qtexengine.dll win\packages\com.qtisas\data\
    - copy libs\Windows-$A\qwt\bin\qwt.dll win\packages\com.qtisas\data\
    - copy libs\Windows-$A\qwtplot3d\bin\qwtplot3d.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\gl2ps\bin\gl2ps.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\gsl\bin\gsl.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\gsl\lib\gsl.lib win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\gsl\bin\gslcblas.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\gsl\lib\gslcblas.lib win\packages\com.qtisas\data\
    - Copy-Item -Path C:\qtisas_libs\$TOOL\gsl\include\gsl -Destination win\packages\com.qtisas\data -Recurse
    - copy C:\qtisas_libs\$TOOL\hdf5\bin\hdf5.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\hdf5\bin\hdf5_cpp.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\muparser\bin\muparser.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\libjpeg\bin\jpeg62.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\tiff\bin\tiff.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\xz\bin\liblzma.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\yaml_cpp\bin\yaml-cpp.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\zlib\bin\zlib.dll win\packages\com.qtisas\data\
    - copy C:\qtisas_libs\$TOOL\zstd\bin\zstd.dll win\packages\com.qtisas\data\
    - mkdir win\packages\com.qtisas\data\python
    - copy qtisas\python\qtisasrc.py win\packages\com.qtisas\data\python
    - copy qtisas\python\python-qtiUtil.py win\packages\com.qtisas\data\python
    - copy qtisas\python\qti_wordlist.txt win\packages\com.qtisas\data\python
    - binarycreator -c win\config\config.xml -p win\packages qtisas-$CI_COMMIT_TAG-$ARCH.exe --verbose
  artifacts:
    paths:
      - qtisas-$CI_COMMIT_TAG-$ARCH.exe

upload:
  stage: upload
  image: curlimages/curl:latest
  only:
    - tags@qtisas/qtisas
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-arm64.dmg "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.dmg"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-intel.dmg "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-intel.dmg"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-arm64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.exe"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./qtisas-$CI_COMMIT_TAG-x64.exe "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-x64.exe"'
  needs: ["macos-release: [arm64, homebrew]",
          "macos-release: [intel, homebrew-x86]",
          "windows-release: [arm64, ARM64, msvc2022_arm64, jcns]",
          "windows-release: [x64, AMD64, msvc2022_64, admin]"]

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags@qtisas/qtisas
  script:
    - echo "Release CI stage for $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    name: $CI_COMMIT_TAG
    description: 'Release created using the release-cli.'
    assets:
      links:
        - name: 'qtisas-$CI_COMMIT_TAG-arm64.dmg'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.dmg'
        - name: 'qtisas-$CI_COMMIT_TAG-intel.dmg'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-intel.dmg'
        - name: 'qtisas-$CI_COMMIT_TAG-arm64.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-arm64.exe'
        - name: 'qtisas-$CI_COMMIT_TAG-x64.exe'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/qtisas-${CI_COMMIT_TAG}-x64.exe'
  needs: ["upload"]

sync:
  stage: sync
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_PROJECT_ID == "1655"'
  image: alpine/git
  script:
    - git remote add mirror https://$GITHUB_TOKEN@github.com/k61n/qtisas.git
    - git fetch mirror
    - git push -f mirror HEAD:master
    - git push -f mirror --delete $(git ls-remote --tags mirror | awk -F/ '{print $NF}')
    - git push mirror --tags
