/******************************************************************************
Project: QtiSAS
License: GNU GPL Version 3 (see LICENSE)
Copyright (C) by the authors:
    2025 Vitaliy Pipich <v.pipich@gmail.com>
Description: Parameters of SANS instruments
 ******************************************************************************/

#pragma once

#include <map>
#include <QSet>
#include <QStringList>

namespace InstrumentSANS
{
const QStringList &KWS1();
const QStringList &KWS1_2020();
const QStringList &KWS1_HE3();

const QStringList &KWS2();
const QStringList &KWS2_HE3_20();
const QStringList &KWS2_He3_10();
const QStringList &KWS2_HRD();

const QStringList &KWS3_2021();
const QStringList &KWS3_VHRD_2021();
const QStringList &KWS3();
const QStringList &KWS3_2016();
const QStringList &KWS3_2017_NICOS();
const QStringList &KWS3_2020();
const QStringList &KWS3_2018();
const QStringList &KWS3_VHRD();
const QStringList &KWS3_VHRD_2020();
const QStringList &KWS3_VHRD_2018();

const QStringList &MARIA();
const QStringList &SANS1();

static const QSet<QString> defaultInstruments = {"KWS1",           "KWS1-2020",       "KWS1-He3",  "KWS2",
                                                 "KWS2-He3-10%",   "KWS2-He3-20%",    "KWS2-HRD",  "KWS3",
                                                 "kws3-2016",      "kws3-2017-nicos", "KWS3-VHRD", "KWS3-VHRD-2018",
                                                 "KWS3-VHRD-2020", "KWS3-2018",       "KWS3-2020", "MARIA",
                                                 "SANS1"};
enum class Parameter
{
    Instrument,
    Instrument_Mode,
    DataFormat,
    Color,
    Input_Folder,
    Include_Sub_Foldes,
    Output_Folder,
    Units_Lambda,
    Units_Appertures,
    Units_Thickness,
    Units_Time,
    Units_Time_RT,
    Units_C,
    Units_C_D_Offset,
    Units_Selector,
    Second_Header_OK,
    Second_Header_Pattern,
    Second_Header_Lines,
    Data_Header_Lines,
    Lines_Between_Frames,
    Pattern,
    Pattern_Select_Data,
    Header_Number_Lines,
    Flexible_Header,
    Flexible_Stop,
    Remove_None_Printable_Symbols,
    Image_Offset_X,
    Image_Offset_Y,
    Image_Data,
    HDF_Data,
    YAML_Data,
    HDF_detector_entry,
    HDF_data_structure,
    YAML_detector_entry,
    XML_base,
    Selector_Read_from_Header,
    Selector_P1,
    Selector_P2,
    Detector_Data_Dimension,
    Detector_Data_Focus,
    Detector_Binning,
    Detector_Pixel_Size,
    Detector_Pixel_Size_Asymetry,
    Detector_Data_Numbers_Per_Line,
    Detector_Data_Tof_Numbers_Per_Line,
    Detector_Data_Transpose,
    Detector_X_to_Minus_X,
    Detector_Y_to_Minus_Y,
    Detector_Dead_Time,
    Detector_Dead_Time_DB,
    Monitor1_Dead_Time,
    Monitor2_Dead_Time,
    Monitor3_Dead_Time,
    Options_2D_DeadTimeModel_NonPara,
    Options_2D_CenterMethod,
    DetRotation_X_Read_from_Header,
    DetRotation_Angle_X,
    DetRotation_Invert_Angle_X,
    DetRotation_Y_Read_from_Header,
    DetRotation_Angle_Y,
    DetRotation_Invert_Angle_Y,
    Calibrant_Type,
    Calibrant,
    Use_Active_Mask_and_Sensitivity_Matrixes,
    Calculate_Calibrant_Transmission_by_Equation,
    Mask_Edge_Shape,
    Mask_BeamStop_Shape,
    Mask_Edge,
    Mask_BeamStop,
    Mask_Edge_Left_X,
    Mask_Edge_Left_Y,
    Mask_Edge_Right_X,
    Mask_Edge_Right_Y,
    Mask_BeamStop_Left_X,
    Mask_BeamStop_Left_Y,
    Mask_BeamStop_Right_X,
    Mask_BeamStop_Right_Y,
    Mask_Dead_Rows,
    Mask_Dead_Cols,
    Mask_Triangular,
    Sensitivity_SpinBoxErrRightLimit,
    Sensitivity_SpinBoxErrLeftLimit,
    Sensitivity_CheckBoxSensError,
    Sensitivity_Tr_Option,
    Sensitivity_in_Use,
    Sensitivity_Masked_Pixels_Value,
    Transmission_Method,
    Options_2D_HighQ,
    Options_2D_HighQ_Parallax_Type,
    Options_2D_HighQ_Tr,
    Options_2D_Polar_Resolusion,
    Options_2D_Mask_Negative_Points,
    Options_2D_Normalization_Type,
    Options_2D_Normalization_Factor,
    Options_2D_Mask_Normalization_BC,
    Options_2D_xyDimension_Pixel,
    Options_2D_Output_Format,
    Options_2D_Header_Output_Format,
    Options_2D_Header_SASVIEW,
    Options_1D_RADmethod_HF,
    Options_1D_RAD_LinearFactor,
    Options_1D_RAD_ProgressiveFactor,
    Options_1D_RemoveFirst,
    Options_1D_RemoveLast,
    Options_1D_RemoveNegativePoints,
    Options_1D_QxQy_From,
    Options_1D_QxQy_To,
    Options_1D_QxQy_BS,
    Options_1D_OutputFormat,
    Options_1D_OutputFormat_PlusHeader,
    Options_1D_Anisotropy,
    Options_1D_AnisotropyAngle,
    Options_1D_QI_Presentation,
    Sample_Position_As_Condition,
    Attenuator_as_Condition,
    Beam_Center_as_Condition,
    Polarization_as_Condition,
    DetectorAngle_as_Condition,
    Reread_Existing_Runs,
    Find_Center_For_EveryFile,
    Tr_Force_Copy_Paste,
    Sampe_Name_As_RunTableName,
    Generate_MergingTable,
    Auto_Merging,
    Overlap_Merging,
    Rewrite_Output,
    Skipt_Tr_Configurations,
    Skipt_Output_Folders,
    Resolusion_Focusing,
    Resolusion_Detector,
    Resolusion_CA_Round,
    Resolusion_SA_Round,
    File_Ext,
    POL_ALIAS_UP,
    POL_ALIAS_DOWN,
    POL_ALIAS_UP_UP,
    POL_ALIAS_UP_DOWN,
    POL_ALIAS_DOWN_DOWN,
    POL_ALIAS_DOWN_UP,
    POLARIZATION,
    POL_TRANSMISSION,
    POL_FLIPPER_EFFICIENCY,
    ANALYZER_TRANSMISSION,
    ANALYZER_EFFICIENCY
};

inline std::map<QString, Parameter> stringToEnumMap = {
    {"Instrument", Parameter::Instrument},
    {"Instrument-Mode", Parameter::Instrument_Mode},
    {"DataFormat", Parameter::DataFormat},
    {"Color", Parameter::Color},
    {"Input-Folder", Parameter::Input_Folder},
    {"Include-Sub-Foldes", Parameter::Include_Sub_Foldes},
    {"Output-Folder", Parameter::Output_Folder},
    {"Units-Lambda", Parameter::Units_Lambda},
    {"Units-Appertures", Parameter::Units_Appertures},
    {"Units-Thickness", Parameter::Units_Thickness},
    {"Units-Time", Parameter::Units_Time},
    {"Units-Time-RT", Parameter::Units_Time_RT},
    {"Units-C", Parameter::Units_C},
    {"Units-C-D-Offset", Parameter::Units_C_D_Offset},
    {"Units-Selector", Parameter::Units_Selector},
    {"2nd-Header-OK", Parameter::Second_Header_OK},
    {"2nd-Header-Pattern", Parameter::Second_Header_Pattern},
    {"2nd-Header-Lines", Parameter::Second_Header_Lines},
    {"Data-Header-Lines", Parameter::Data_Header_Lines},
    {"Lines-Between-Frames", Parameter::Lines_Between_Frames},
    {"Pattern", Parameter::Pattern},
    {"Pattern-Select-Data", Parameter::Pattern_Select_Data},
    {"Header-Number-Lines", Parameter::Header_Number_Lines},
    {"Flexible-Header", Parameter::Flexible_Header},
    {"Flexible-Stop", Parameter::Flexible_Stop},
    {"Remove-None-Printable-Symbols", Parameter::Remove_None_Printable_Symbols},
    {"Image-Offset-X", Parameter::Image_Offset_X},
    {"Image-Offset-Y", Parameter::Image_Offset_Y},
    {"Image-Data", Parameter::Image_Data},
    {"HDF-Data", Parameter::HDF_Data},
    {"YAML-Data", Parameter::YAML_Data},
    {"HDF-detector-entry", Parameter::HDF_detector_entry},
    {"HDF-data-structure", Parameter::HDF_data_structure},
    {"YAML-detector-entry", Parameter::YAML_detector_entry},
    {"XML-base", Parameter::XML_base},
    {"Selector-Read-from-Header", Parameter::Selector_Read_from_Header},
    {"Selector-P1", Parameter::Selector_P1},
    {"Selector-P2", Parameter::Selector_P2},
    {"Detector-Data-Dimension", Parameter::Detector_Data_Dimension},
    {"Detector-Data-Focus", Parameter::Detector_Data_Focus},
    {"Detector-Binning", Parameter::Detector_Binning},
    {"Detector-Pixel-Size", Parameter::Detector_Pixel_Size},
    {"Detector-Pixel-Size-Asymetry", Parameter::Detector_Pixel_Size_Asymetry},
    {"Detector-Data-Numbers-Per-Line", Parameter::Detector_Data_Numbers_Per_Line},
    {"Detector-Data-Tof-Numbers-Per-Line", Parameter::Detector_Data_Tof_Numbers_Per_Line},
    {"Detector-Data-Transpose", Parameter::Detector_Data_Transpose},
    {"Detector-X-to-Minus-X", Parameter::Detector_X_to_Minus_X},
    {"Detector-Y-to-Minus-Y", Parameter::Detector_Y_to_Minus_Y},
    {"Detector-Dead-Time", Parameter::Detector_Dead_Time},
    {"Detector-Dead-Time-DB", Parameter::Detector_Dead_Time_DB},
    {"Monitor1-Dead-Time", Parameter::Monitor1_Dead_Time},
    {"Monitor2-Dead-Time", Parameter::Monitor2_Dead_Time},
    {"Monitor3-Dead-Time", Parameter::Monitor3_Dead_Time},
    {"Options-2D-DeadTimeModel-NonPara", Parameter::Options_2D_DeadTimeModel_NonPara},
    {"Options-2D-CenterMethod", Parameter::Options_2D_CenterMethod},
    {"DetRotation-X-Read-from-Header", Parameter::DetRotation_X_Read_from_Header},
    {"DetRotation-Angle-X", Parameter::DetRotation_Angle_X},
    {"DetRotation-Invert-Angle-X", Parameter::DetRotation_Invert_Angle_X},
    {"DetRotation-Y-Read-from-Header", Parameter::DetRotation_Y_Read_from_Header},
    {"DetRotation-Angle-Y", Parameter::DetRotation_Angle_Y},
    {"DetRotation-Invert-Angle-Y", Parameter::DetRotation_Invert_Angle_Y},
    {"Calibrant-Type", Parameter::Calibrant_Type},
    {"Calibrant", Parameter::Calibrant},
    {"Use-Active-Mask-and-Sensitivity-Matrixes", Parameter::Use_Active_Mask_and_Sensitivity_Matrixes},
    {"Calculate-Calibrant-Transmission-by-Equation", Parameter::Calculate_Calibrant_Transmission_by_Equation},
    {"Mask-Edge-Shape", Parameter::Mask_Edge_Shape},
    {"Mask-BeamStop-Shape", Parameter::Mask_BeamStop_Shape},
    {"Mask-Edge", Parameter::Mask_Edge},
    {"Mask-BeamStop", Parameter::Mask_BeamStop},
    {"Mask-Edge-Left-X", Parameter::Mask_Edge_Left_X},
    {"Mask-Edge-Left-Y", Parameter::Mask_Edge_Left_Y},
    {"Mask-Edge-Right-X", Parameter::Mask_Edge_Right_X},
    {"Mask-Edge-Right-Y", Parameter::Mask_Edge_Right_Y},
    {"Mask-BeamStop-Left-X", Parameter::Mask_BeamStop_Left_X},
    {"Mask-BeamStop-Left-Y", Parameter::Mask_BeamStop_Left_Y},
    {"Mask-BeamStop-Right-X", Parameter::Mask_BeamStop_Right_X},
    {"Mask-BeamStop-Right-Y", Parameter::Mask_BeamStop_Right_Y},
    {"Mask-Dead-Rows", Parameter::Mask_Dead_Rows},
    {"Mask-Dead-Cols", Parameter::Mask_Dead_Cols},
    {"Mask-Triangular", Parameter::Mask_Triangular},
    {"Sensitivity-SpinBoxErrRightLimit", Parameter::Sensitivity_SpinBoxErrRightLimit},
    {"Sensitivity-SpinBoxErrLeftLimit", Parameter::Sensitivity_SpinBoxErrLeftLimit},
    {"Sensitivity-CheckBoxSensError", Parameter::Sensitivity_CheckBoxSensError},
    {"Sensitivity-Tr-Option", Parameter::Sensitivity_Tr_Option},
    {"Sensitivity-in-Use", Parameter::Sensitivity_in_Use},
    {"Sensitivity-Masked-Pixels-Value", Parameter::Sensitivity_Masked_Pixels_Value},
    {"Transmission-Method", Parameter::Transmission_Method},
    {"Options-2D-HighQ", Parameter::Options_2D_HighQ},
    {"Options-2D-HighQ-Parallax-Type", Parameter::Options_2D_HighQ_Parallax_Type},
    {"Options-2D-HighQ-Tr", Parameter::Options_2D_HighQ_Tr},
    {"Options-2D-Polar-Resolusion", Parameter::Options_2D_Polar_Resolusion},
    {"Options-2D-Mask-Negative-Points", Parameter::Options_2D_Mask_Negative_Points},
    {"Options-2D-Normalization-Type", Parameter::Options_2D_Normalization_Type},
    {"Options-2D-Normalization-Factor", Parameter::Options_2D_Normalization_Factor},
    {"Options-2D-Mask-Normalization-BC", Parameter::Options_2D_Mask_Normalization_BC},
    {"Options-2D-xyDimension-Pixel", Parameter::Options_2D_xyDimension_Pixel},
    {"Options-2D-Output-Format", Parameter::Options_2D_Output_Format},
    {"Options-2D-Header-Output-Format", Parameter::Options_2D_Header_Output_Format},
    {"Options-2D-Header-SASVIEW", Parameter::Options_2D_Header_SASVIEW},
    {"Options-1D-RADmethod-HF", Parameter::Options_1D_RADmethod_HF},
    {"Options-1D-RAD-LinearFactor", Parameter::Options_1D_RAD_LinearFactor},
    {"Options-1D-RAD-ProgressiveFactor", Parameter::Options_1D_RAD_ProgressiveFactor},
    {"Options-1D-RemoveFirst", Parameter::Options_1D_RemoveFirst},
    {"Options-1D-RemoveLast", Parameter::Options_1D_RemoveLast},
    {"Options-1D-RemoveNegativePoints", Parameter::Options_1D_RemoveNegativePoints},
    {"Options-1D-QxQy-From", Parameter::Options_1D_QxQy_From},
    {"Options-1D-QxQy-To", Parameter::Options_1D_QxQy_To},
    {"Options-1D-QxQy-BS", Parameter::Options_1D_QxQy_BS},
    {"Options-1D-OutputFormat", Parameter::Options_1D_OutputFormat},
    {"Options-1D-OutputFormat-PlusHeader", Parameter::Options_1D_OutputFormat_PlusHeader},
    {"Options-1D-Anisotropy", Parameter::Options_1D_Anisotropy},
    {"Options-1D-AnisotropyAngle", Parameter::Options_1D_AnisotropyAngle},
    {"Options-1D-QI-Presentation", Parameter::Options_1D_QI_Presentation},
    {"Sample-Position-As-Condition", Parameter::Sample_Position_As_Condition},
    {"Attenuator-as-Condition", Parameter::Attenuator_as_Condition},
    {"Beam-Center-as-Condition", Parameter::Beam_Center_as_Condition},
    {"Polarization-as-Condition", Parameter::Polarization_as_Condition},
    {"DetectorAngle-as-Condition", Parameter::DetectorAngle_as_Condition},
    {"Reread-Existing-Runs", Parameter::Reread_Existing_Runs},
    {"Find-Center-For-EveryFile", Parameter::Find_Center_For_EveryFile},
    {"Tr-Force-Copy-Paste", Parameter::Tr_Force_Copy_Paste},
    {"Sampe-Name-As-RunTableName", Parameter::Sampe_Name_As_RunTableName},
    {"Generate-MergingTable", Parameter::Generate_MergingTable},
    {"Auto-Merging", Parameter::Auto_Merging},
    {"Overlap-Merging", Parameter::Overlap_Merging},
    {"Rewrite-Output", Parameter::Rewrite_Output},
    {"Skipt-Tr-Configurations", Parameter::Skipt_Tr_Configurations},
    {"Skipt-Output-Folders", Parameter::Skipt_Output_Folders},
    {"Resolusion-Focusing", Parameter::Resolusion_Focusing},
    {"Resolusion-Detector", Parameter::Resolusion_Detector},
    {"Resolusion-CA-Round", Parameter::Resolusion_CA_Round},
    {"Resolusion-SA-Round", Parameter::Resolusion_SA_Round},
    {"File-Ext", Parameter::File_Ext},
    {"POL-ALIAS-UP", Parameter::POL_ALIAS_UP},
    {"POL-ALIAS-DOWN", Parameter::POL_ALIAS_DOWN},
    {"POL-ALIAS-UP-UP", Parameter::POL_ALIAS_UP_UP},
    {"POL-ALIAS-UP-DOWN", Parameter::POL_ALIAS_UP_DOWN},
    {"POL-ALIAS-DOWN-DOWN", Parameter::POL_ALIAS_DOWN_DOWN},
    {"POL-ALIAS-DOWN-UP", Parameter::POL_ALIAS_DOWN_UP},
    {"POLARIZATION", Parameter::POLARIZATION},
    {"POL-TRANSMISSION", Parameter::POL_TRANSMISSION},
    {"POL-FLIPPER-EFFICIENCY", Parameter::POL_FLIPPER_EFFICIENCY},
    {"ANALYZER-TRANSMISSION", Parameter::ANALYZER_TRANSMISSION},
    {"ANALYZER-EFFICIENCY", Parameter::ANALYZER_EFFICIENCY}
};
}

