#!/bin/zsh

export CONTENTS=$(dirname $(dirname -- $(readlink -f -- $0)))
export PYTHONHOME=$CONTENTS/Resources/%python%
export PYTHONPATH=~/.config/qtisas/python/site-packages
export QT_PLUGIN_PATH=$PYTHONHOME/lib/%python%/site-packages/PyQt6/Qt6/plugins
export PYTHONDONTWRITEBYTECODE=1
exec $CONTENTS/MacOS/qtisas "$@"
