
if (${PREFER_QT})
    if (${PREFER_QT} EQUAL 6)
        set(QT_MODULES Core DBus Network OpenGLWidgets PrintSupport Svg Xml Widgets)
    elseif (${PREFER_QT} EQUAL 5)
        set(QT_MODULES Core Network OpenGL PrintSupport Svg Xml Widgets)
    endif ()
    set(V ${PREFER_QT})
    find_package(Qt${V} COMPONENTS ${QT_MODULES} REQUIRED)
else ()
    set(QT_MODULES Core DBus Network OpenGLWidgets PrintSupport Svg Xml Widgets)
    find_package(Qt6 COMPONENTS ${QT_MODULES} QUIET)
    if (${Qt6_FOUND})
        set(V 6)
    else ()
        set(QT_MODULES Core Network OpenGL PrintSupport Svg Xml Widgets)
        find_package(Qt5 COMPONENTS ${QT_MODULES} REQUIRED)
        set(V 5)
    endif ()
endif ()

message(STATUS "Found Qt: ${Qt${V}Core_VERSION}")
foreach (module IN LISTS QT_MODULES)
    get_target_property(module_path Qt${V}::${module} LOCATION)
    message(STATUS "Found ${module}: ${module_path}")
endforeach ()
