
if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    find_program(QMAKE NAMES qmake6 qmake-qt5 qmake REQUIRED)
elseif (APPLE)
    # need to climb up directories 
    set(CONTINUE_LOOP ON)
    while (CONTINUE_LOOP)
        get_filename_component (PARENT_DIR "${QT_LIB_PATH}" DIRECTORY)
        if (PARENT_DIR STREQUAL QT_LIB_PATH)
            break ()
        endif ()
        set (QT_LIB_PATH "${PARENT_DIR}")
        get_filename_component (DIRNAME "${QT_LIB_PATH}" NAME)
        if (DIRNAME MATCHES "^qt(@?[56])?$")
            set(CONTINUE_LOOP OFF)
        endif ()
    endwhile ()
    find_program(QMAKE NAMES qmake HINTS ${QT_LIB_PATH}/bin NO_DEFAULT_PATH REQUIRED)
else (WIN32)
    get_filename_component (QT_LIB_PATH "${QT_LIB_PATH}" DIRECTORY)
    find_program(QMAKE NAMES qmake HINTS ${QT_LIB_PATH} NO_DEFAULT_PATH REQUIRED)
endif ()
message(STATUS "Found qmake: ${QMAKE}")
