
set(LIBRARIES
    "alglib" "minigzip" "qtexengine" "qwt" "qwtplot3d" "tamuanova")
set(QTISAS_LIBS "")
foreach (lib ${LIBRARIES})
    add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/${lib})
    if (TARGET ${lib}_shared)
        list(APPEND QTISAS_LIBS ${lib}_shared)
        message(STATUS "${lib} will be provided by target ${lib}_shared")
    elseif (TARGET ${lib}_static)
        list(APPEND QTISAS_LIBS ${lib}_static)
        message(STATUS "${lib} will be provided by target ${lib}_static")
    else ()
        message(FATAL_ERROR "Target for ${lib} not found")
    endif ()

    file(GLOB_RECURSE HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/${lib}/include/*.h")
    if(HEADERS)
        file(COPY ${HEADERS} DESTINATION "${CMAKE_CURRENT_BINARY_DIR}/3rdparty/include/${lib}")
    endif()
endforeach ()
include_directories(${CMAKE_CURRENT_BINARY_DIR}/3rdparty/include/)
